services:
  umbrel:
    build:
      context: .
      dockerfile: Dockerfile
    image: umbrel-os:local
    container_name: umbrel
    pid: host
    ports:
      - 80
    volumes:
      - umbrel_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: always
    stop_grace_period: 1m
    labels:
      - traefik.http.middlewares.forzar-headers.headers.customrequestheaders.X-Forwarded-Proto=https
      - traefik.http.middlewares.forzar-headers.headers.customrequestheaders.X-Forwarded-Host=os.dominic.pw
      - traefik.http.routers.n8n-umbrelos-oazure-186-websecure.middlewares=forzar-headers

volumes:
  umbrel_data:
