services:
  umbrel:
    build:
      context: .
      dockerfile: Dockerfile
    image: dockurr/umbrel:latest
    container_name: umbrel
    pid: host
    ports:
      - 80:80
    volumes:
      - ./umbrel:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    stop_grace_period: 1m
    labels:
      # 1. Creamos un middleware llamado "forzar-headers" con tus datos
      - traefik.http.middlewares.forzar-headers.headers.customrequestheaders.X-Forwarded-Proto=https
      - traefik.http.middlewares.forzar-headers.headers.customrequestheaders.X-Forwarded-Host=os.dominic.pw
      - traefik.http.routers.n8n-umbrelos-oazure-186-websecure.middlewares=umbrel-headers
      # 2. Le asignamos este middleware a tu router seguro (websecure)
      #- traefik.http.routers.n8numbrelos-oazure-186-websecure.middlewares=forzar-headers
