import nodePath from 'node:path'

import fse from 'fs-extra'
import {$} from 'execa'

import randomToken from '../utilities/random-token.js'

import type Umbreld from '../../index.js'
import type {FileChangeEvent} from './watcher.js'

const SMB_CONFIG = `# Generated by umbreld

[global]
server role = standalone
server string = Umbrel
mdns name = mdns
logging = systemd
log file = /dev/null
access based share enum = yes
restrict anonymous = 2
map to guest = never
vfs objects = catia fruit streams_xattr
fruit:metadata = stream
fruit:model = MacSamba
fruit:veto_appledouble = no
fruit:nfs_aces = no
fruit:wipe_intentionally_left_blank_rfork = yes
fruit:delete_empty_adfiles = yes
fruit:posix_rename = yes
load printers = no
disable spoolss = yes
`

const shareConfig = (name: string, path: string) => `
# Share specific config
[${name}]
path = ${path}
writeable = yes
valid users = umbrel
force user = root
force group = umbrel
inherit owner = yes
fruit:time machine = yes
`

export default class Samba {
	#umbreld: Umbreld
	logger: Umbreld['logger']
	#removeFileChangeListener?: () => void
	#removeExternalStorageChangeListener?: () => void

	constructor(umbreld: Umbreld) {
		this.#umbreld = umbreld
		const {name} = this.constructor
		this.logger = umbreld.logger.createChildLogger(`files:${name.toLocaleLowerCase()}`)
	}

	async start() {
		this.logger.log('Starting samba')

		// Skip Samba setup in Docker where samba tools and config don't exist
		const isDocker = await fse.pathExists('/.dockerenv').catch(() => false)
		if (isDocker) {
			this.logger.log('Skipping samba setup in Docker environment')
			return
		}

		await this.applySharePassword().catch((error) => {
			this.logger.error(`Failed to apply share password`, error)
		})

		await this.applyShares().catch((error) => {
			this.logger.error(`Failed to apply shares`, error)
		})

		this.#removeFileChangeListener = this.#umbreld.eventBus.on(
			'files:watcher:change',
			this.#handleFileChange.bind(this),
		)

		this.#removeExternalStorageChangeListener = this.#umbreld.eventBus.on('files:external-storage:change', () => {
			this.applyShares().catch((error) => this.logger.error('Failed to reapply shares', error))
		})
	}

	async stop() {
		this.logger.log('Stopping samba')
		this.#removeFileChangeListener?.()
		this.#removeExternalStorageChangeListener?.()

		// Skip systemctl commands in Docker where they won't work
		const isDocker = await fse.pathExists('/.dockerenv').catch(() => false)
		if (isDocker) return

		await $`systemctl stop smbd`.catch((error) => this.logger.error(`Failed to stop samba`, error))
		await $`systemctl stop wsdd2`.catch((error) => this.logger.error(`Failed to stop wsdd2`, error))
	}

	async getSharePassword() {
		const sharePasswordFile = `${this.#umbreld.dataDirectory}/secrets/share-password`

		const sharePassword = await fse.readFile(sharePasswordFile, 'utf8').catch(async () => {
			this.logger.log('Creating share password on first run')
			const sharePassword = randomToken(128)
			await fse.writeFile(sharePasswordFile, sharePassword)
			return sharePassword
		})

		return sharePassword
	}

	async applySharePassword() {
		const sharePassword = await this.getSharePassword()
		await $({
			input: `${sharePassword}\n${sharePassword}\n`,
		})`smbpasswd -s -a umbrel`
	}

	async applyShares({excludePaths}: {excludePaths?: string[]} = {}) {
		// Skip samba shares in Docker where samba is not available
		const isDocker = await fse.pathExists('/.dockerenv').catch(() => false)
		if (isDocker) return

		const shares = await this.#get()

		let config = SMB_CONFIG
		let activeShare = 0
		const sharesToClose: string[] = []

		for (const share of shares) {
			const systemPath = await this.#umbreld.files.virtualToSystemPath(share.path)

			if (!(await fse.pathExists(systemPath))) continue

			if (excludePaths?.some((p) => share.path === p || share.path.startsWith(p + '/'))) {
				const sharename = await this.#computeSharename(share.name, share.path)
				sharesToClose.push(sharename)
				continue
			}

			const name = await this.#computeSharename(share.name, share.path)

			config += shareConfig(name, systemPath)
			activeShare++
		}

		for (const sharename of sharesToClose) {
			this.logger.log(`Closing share '${sharename}'`)
			await $`smbcontrol smbd close-share ${sharename}`.catch((error) => {
				this.logger.error(`Failed to close share '${sharename}'`, error)
			})
		}

		await fse.writeFile('/etc/samba/smb.conf', config)

		if (activeShare === 0) return await $`systemctl stop smbd`

		await $`systemctl start smbd`
		await $`smbcontrol smbd reload-config`

		await $`systemctl start wsdd2`
	}

	async #computeSharename(name: string, path: string) {
		let sharename = `${name} (Umbrel)`
		if (path === '/Home') {
			const user = await this.#umbreld.user.get()
			const username = user?.name
			if (username) sharename = `${username}'s Umbrel`
		}
		return sharename
	}

	async #get() {
		const shares = await this.#umbreld.store.get('files.shares')
		return shares || []
	}

	async #handleFileChange(event: FileChangeEvent) {
		if (event.type !== 'delete') return
		const shares = await this.#get()
		const virtualDeletedPath = this.#umbreld.files.systemToVirtualPath(event.path)
		const deletedShares = shares.filter(
			(share) => share.path === virtualDeletedPath || share.path.startsWith(virtualDeletedPath + '/'),
		)
		for (const share of deletedShares) await this.removeShare(share.path)
	}

	async listShares() {
		const shares = await this.#get()

		const sharesWithStatus = await Promise.all(
			shares.map(async (share) => {
				const systemPath = await this.#umbreld.files.virtualToSystemPath(share.path)
				return {
					...share,
					available: await fse.pathExists(systemPath),
					sharename: await this.#computeSharename(share.name, share.path),
				}
			}),
		)

		return sharesWithStatus
	}

	async addShare(virtualPath: string) {
		const allowedOperations = await this.#umbreld.files.getAllowedOperations(virtualPath)
		if (!allowedOperations.includes('share')) throw new Error('[operation-not-allowed]')

		this.logger.log(`Adding share for ${virtualPath}`)

		await this.#umbreld.store.getWriteLock(async ({set}) => {
			const shares = await this.#get()

			const shareExists = shares.some((share) => share.path === virtualPath)
			if (shareExists) throw new Error('[share-already-exists]')

			let name = nodePath.basename(virtualPath)
			let i = 1
			while (shares.some((share) => share.name === name)) {
				i++
				if (i > 10) throw new Error('[share-name-generation-failed]')
				name = `${nodePath.basename(virtualPath)} (${i})`
			}

			await set('files.shares', [...shares, {name, path: virtualPath}])
		})

		await this.applyShares()

		return virtualPath
	}

	async removeShare(virtualPath: string) {
		this.logger.log(`Removing share for ${virtualPath}`)

		let deleted = false
		await this.#umbreld.store.getWriteLock(async ({set}) => {
			const shares = await this.#get()
			const newShares = shares.filter((share) => share.path !== virtualPath)
			deleted = newShares.length < shares.length
			if (deleted) await set('files.shares', newShares)
		})

		if (deleted) {
			await this.applyShares()
		}

		return deleted
	}
}
